server:
  port: 8084

spring:
  application:
    name: AUTH-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: 8767780674

  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:file:application-secret.yml

eureka:
  instance:
    prefer-ip-address: true
    register-with-service: true
    service-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

